fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    nodejs: "https://github.com/voxpupuli/puppet-nodejs.git"
  symlinks:
    wintersmith: "#{source_dir}"
